---
title: "test"
author: "Gary Liu"
date: "2018/5/26"
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = T, warning = F, 
                      message = F, error = F)
knitr::opts_knit$set(root.dir = normalizePath("/Users/garyliu/Documents/報告/經濟部落客競賽/Web/content/post"))

library(ggplot2)
theme_set(theme_bw() +
  theme(text = element_text(family = "DFKaiShu-SB-Estd-BF"),
        axis.text.x = element_text(angle = 90, size = 13),
        axis.text.y = element_text(size = 13),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        legend.text = element_text(size = 13),
        plot.title = element_text(hjust = 0.5, size = 16),
        plot.margin = unit(c(0.4,0.5,1.5,0.5),"cm")))
```

#Introduction
####1. 人口密度
```{r scraping}
#爬蟲
library(rvest)
url <- "https://zh.wikipedia.org/wiki/臺灣行政區人口密度表"

url %>% read_html() %>%
  html_nodes(xpath = '//*[@id="mw-content-text"]/div/table[2]') %>%
  html_table(fill=TRUE) %>%
  as.data.frame(stringAsFactors = F)-> dense
```

```{r clean for density}
library(dplyr)
library(magrittr)
#clean ','
dense$人口密度 <- gsub(pattern = ',', replacement = '', x = dense$人口密度)
#資料格式
dense$人口密度 <- as.numeric(dense$人口密度)
dense$名稱 <- factor(dense$名稱, levels = unique(dense$名稱))

dense$類別 <- factor(dense$類別, levels = unique(dense$類別))

```


```{r barplot for density, fig.align='center'}
library(plotly)
library(shiny)
dense %>%
ggplot(data=., aes(x = 名稱, y = 人口密度, fill = 類別)) +
    geom_bar(stat="identity") +
    labs(x = '', fill = '') -> g
g1 <- ggplotly(g)
div(subplot(g1, margin = 0.1), align = "center")
```